openapi: 3.0.0
info:
  title: AirBean RESTful API
  description: API documentation using Swagger
  version: 1.0.0

tags:
  - name: Orders
    description: All endpoints related to customer orders

paths: {}
